services:
  vhub-mysql:
    image: mysql:9.0.1
    restart: unless-stopped
    container_name: vhub-mysql
    networks:
      vhub_net:
        ipv4_address: 172.28.1.4
    volumes:
      - /opt/vhub-data-mysql:/var/lib/mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: vhub-mysql

  vhub-minio:
    image: bitnami/minio:2024.8.3
    restart: unless-stopped
    container_name: vhub-minio
    networks:
      vhub_net:
        ipv4_address: 172.28.1.3
    volumes:
      - /opt/vhub-data-minio:/bitnami/minio/data
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: vhub-minio
      MINIO_ROOT_PASSWORD: vhub-minio
      MINIO_DEFAULT_BUCKETS: vhub
  
  vhub-app:
    image: vhub:latest
    restart: unless-stopped
    container_name: vhub-app
    networks:
      vhub_net:
        ipv4_address: 172.28.1.2
    volumes:
      - /opt/vhub-app/logs:/app/logs
    depends_on:
      - vhub-minio
      - vhub-mysql

  vhub-nginx:
    image: nginx:1.27.1-alpine3.20
    restart: unless-stopped
    container_name: vhub-nginx
    networks:
      vhub_net:
        ipv4_address: 172.28.1.1
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - vhub-app
    volumes:
      - /opt/vhub-nginx/conf.d:/etc/nginx/conf.d
      - /opt/vhub-nginx/ssl:/etc/nginx/ssl

networks:
  vhub_net:
    ipam:
      driver: default
      config:
        - subnet: 172.28.0.0/16